#!/bin/sh
# -*- sh -*-

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

# If run with the "config"-parameter, give out information on how the
# graphs should look.

if [ "$1" = "config" ]; then

        echo 'graph_title Upstream channels frequencies'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel MHz'
        echo 'graph_category upc'
        echo 'graph_info The frequencies of the cable modems upstream channels.'
	wget --header "Cookie: name=session" --quiet --user="$routeruser" --password="$routerpassword" -O - http://$routerip/BasicLan.asp p|sed 's,</tr>,\n,g' |grep '>RF Parameters - Upstream' -A 11 |grep dBmV |sed -e "s,<[^<^>]*>,:,g" |awk -F: '{print "channel" $3 ".label channel " $3 "\nchannel" $3 ".draw LINE2\nchannel" $3 ".info Frequency for upstream channel " $3 " in MHz" }'
        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.
wget --header "Cookie: name=session" --quiet --user="$routeruser" --password="$routerpassword" -O - http://$routerip/BasicLan.asp|sed 's,</tr>,\n,g' |grep '>RF Parameters - Upstream' -A 11 |grep dBmV |sed -e "s,<[^<^>]*>,:,g" -e "s,MHz,,g" |awk -F: '{print "channel" $3 ".value " $5}'
