#!/bin/sh
# -*- sh -*-

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

# If run with the "config"-parameter, give out information on how the
# graphs should look.

if [ "$1" = "config" ]; then

        echo 'graph_title Upstream channel ids symbol rates'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel Ksym/sec'
        echo 'graph_category upc'
        echo 'graph_info The symbol rates of the cable modem channel ids.'
	wget --header "Cookie: name=session" --quiet --user="$routeruser" --password="$routerpassword" -O - http://$routerip/RgConnect.asp |grep '>Upstream Channels' -A 11 | grep Locked |sed -e "s,<[^<^>]*>,:,g" |awk -F: '{print "channelid" $9 ".label channel id " $9 "\nchannelid" $9 ".draw LINE2\nchannelid" $9 ".info Symbol rate for upstream channel id " $9 }'
        exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.

wget --header "Cookie: name=session" --quiet --user="$routeruser" --password="$routerpassword" -O - http://$routerip/RgConnect.asp |grep '>Upstream Channels' -A 11 | grep Locked |sed -e "s,<[^<^>]*>,:,g" -e "s,Ksym/sec,,g" |awk -F: '{print "channelid" $9 ".value " $11}'
